export const FIXED_SUGGESTION: Record<string, string> = {
  English: 'What is wrong with this world?',
  Dutch: 'Wat is er mis met deze wereld?',
  French: "Qu'est-ce qui ne va pas dans ce monde?",
  German: 'Was stimmt nicht mit dieser Welt?',
};

export const SUGGESTION_POOL: Record<string, string[]> = {
  English: [
    'What is time?',
    'What is meaning?',
    'What is value?',
    'Why does something feel right or wrong?',
    'What is justice?',
    'What is the self?',
    'Is free will real?',
    'What is consciousness?',
    'Why do we fear death?',
    'What do we owe each other?',
    'Can we ever truly know anything?',
    'What makes a life well-lived?',
    'Why is there something rather than nothing?',
    'What is beauty?',
    'Is happiness the point of life?',
    'What is truth?',
    'Why do good people do bad things?',
    'What is power?',
    'Can violence ever be justified?',
    'What is love?',
    'Why do humans need meaning?',
    'Is morality invented or discovered?',
    'What is friendship?',
    'What is courage?',
    'What is humility?',
    'Can we ever truly know another person?',
    'What is the good life?',
    'Is equality a natural condition or a political achievement?',
    'What makes art meaningful?',
    'Is suffering necessary for growth?',
    'What do we owe future generations?',
    'Can there be progress in ethics?',
    'What is the relationship between language and thought?',
    'Is there such a thing as a self?',
    'What is the nature of evil?',
    'Can reason alone guide us?',
    'What is the purpose of suffering?',
    'Is democracy the best form of government?',
    'What is the difference between knowledge and belief?',
    'Can we be held responsible for who we are?',
    'What is the relationship between body and mind?',
    'Is there an objective reality?',
    'What is dignity?',
    'What is the relationship between freedom and responsibility?',
    'Can forgiveness be rational?',
    'What is home?',
    'Is there meaning in impermanence?',
    'What is a good death?',
    'What do we owe those who came before us?',
    'Is loneliness a philosophical problem?',
    'What is silence?',
  ],
  Dutch: [
    'Wat is tijd?',
    'Wat is betekenis?',
    'Wat is waarde?',
    'Waarom voelt iets goed of fout?',
    'Wat is rechtvaardigheid?',
    'Wat is het zelf?',
    'Is vrije wil echt?',
    'Wat is bewustzijn?',
    'Waarom zijn we bang voor de dood?',
    'Wat zijn we elkaar verschuldigd?',
    'Kunnen we ooit iets echt weten?',
    'Wat maakt een leven de moeite waard?',
    'Waarom bestaat er iets in plaats van niets?',
    'Wat is schoonheid?',
    'Is geluk het doel van het leven?',
    'Wat is waarheid?',
    'Waarom doen goede mensen slechte dingen?',
    'Wat is macht?',
    'Kan geweld ooit gerechtvaardigd zijn?',
    'Wat is liefde?',
    'Waarom hebben mensen betekenis nodig?',
    'Is moraliteit uitgevonden of ontdekt?',
    'Wat is vriendschap?',
    'Wat is moed?',
    'Wat is bescheidenheid?',
    'Kunnen we een ander ooit echt kennen?',
    'Wat is het goede leven?',
    'Is gelijkheid een natuurlijke toestand of een politieke verworvenheid?',
    'Wat maakt kunst betekenisvol?',
    'Is lijden noodzakelijk voor groei?',
    'Wat zijn we toekomstige generaties verschuldigd?',
    'Kan er vooruitgang zijn in de ethiek?',
    'Wat is de relatie tussen taal en denken?',
    'Bestaat er zoiets als een zelf?',
    'Wat is de aard van het kwaad?',
    'Kan de rede ons alleen leiden?',
    'Wat is het doel van lijden?',
    'Is democratie de beste regeringsvorm?',
    'Wat is het verschil tussen kennis en geloof?',
    'Kunnen we verantwoordelijk worden gehouden voor wie we zijn?',
    'Wat is de relatie tussen lichaam en geest?',
    'Is er een objectieve werkelijkheid?',
    'Wat is waardigheid?',
    'Wat is de relatie tussen vrijheid en verantwoordelijkheid?',
    'Kan vergeven rationeel zijn?',
    'Wat is thuis?',
    'Is er betekenis in vergankelijkheid?',
    'Wat is een goede dood?',
    'Wat zijn we verschuldigd aan hen die voor ons kwamen?',
    'Is eenzaamheid een filosofisch probleem?',
    'Wat is stilte?',
  ],
  French: [
    "Qu'est-ce que le temps?",
    "Qu'est-ce que le sens?",
    "Qu'est-ce que la valeur?",
    'Pourquoi quelque chose semble-t-il juste ou faux?',
    "Qu'est-ce que la justice?",
    "Qu'est-ce que le soi?",
    'Le libre arbitre est-il réel?',
    "Qu'est-ce que la conscience?",
    'Pourquoi craignons-nous la mort?',
    'Que nous devons-nous mutuellement?',
    'Peut-on jamais vraiment savoir quelque chose?',
    "Qu'est-ce qui rend une vie bien vécue?",
    'Pourquoi y a-t-il quelque chose plutôt que rien?',
    "Qu'est-ce que la beauté?",
    'Le bonheur est-il le but de la vie?',
    "Qu'est-ce que la vérité?",
    'Pourquoi les bonnes personnes font-elles de mauvaises choses?',
    "Qu'est-ce que le pouvoir?",
    'La violence peut-elle jamais être justifiée?',
    "Qu'est-ce que l'amour?",
    'Pourquoi les humains ont-ils besoin de sens?',
    'La moralité est-elle inventée ou découverte?',
    "Qu'est-ce que l'amitié?",
    "Qu'est-ce que le courage?",
    "Qu'est-ce que l'humilité?",
    'Peut-on jamais vraiment connaître autrui?',
    "Qu'est-ce que la bonne vie?",
    "L'égalité est-elle une condition naturelle ou une conquête politique?",
    "Qu'est-ce qui rend l'art significatif?",
    'La souffrance est-elle nécessaire à la croissance?',
    'Que devons-nous aux générations futures?',
    'Peut-il y avoir un progrès en éthique?',
    'Quelle est la relation entre le langage et la pensée?',
    'Existe-t-il quelque chose comme un soi?',
    'Quelle est la nature du mal?',
    'La raison seule peut-elle nous guider?',
    'Quel est le but de la souffrance?',
    'La démocratie est-elle la meilleure forme de gouvernement?',
    'Quelle est la différence entre connaissance et croyance?',
    "Peut-on être tenu responsable de ce que l'on est?",
    "Quelle est la relation entre le corps et l'esprit?",
    'Existe-t-il une réalité objective?',
    "Qu'est-ce que la dignité?",
    'Quelle est la relation entre liberté et responsabilité?',
    'Le pardon peut-il être rationnel?',
    "Qu'est-ce que le foyer?",
    "Y a-t-il un sens dans l'impermanence?",
    "Qu'est-ce qu'une bonne mort?",
    'Que devons-nous à ceux qui nous ont précédés?',
    'La solitude est-elle un problème philosophique?',
    "Qu'est-ce que le silence?",
  ],
  German: [
    'Was ist Zeit?',
    'Was ist Bedeutung?',
    'Was ist Wert?',
    'Warum fühlt sich etwas richtig oder falsch an?',
    'Was ist Gerechtigkeit?',
    'Was ist das Selbst?',
    'Ist freier Wille real?',
    'Was ist Bewusstsein?',
    'Warum fürchten wir den Tod?',
    'Was schulden wir einander?',
    'Können wir jemals wirklich etwas wissen?',
    'Was macht ein Leben lebenswert?',
    'Warum gibt es etwas statt nichts?',
    'Was ist Schönheit?',
    'Ist Glück der Sinn des Lebens?',
    'Was ist Wahrheit?',
    'Warum tun gute Menschen schlechte Dinge?',
    'Was ist Macht?',
    'Kann Gewalt jemals gerechtfertigt sein?',
    'Was ist Liebe?',
    'Warum brauchen Menschen Bedeutung?',
    'Ist Moral erfunden oder entdeckt?',
    'Was ist Freundschaft?',
    'Was ist Mut?',
    'Was ist Demut?',
    'Können wir einen anderen Menschen jemals wirklich kennen?',
    'Was ist das gute Leben?',
    'Ist Gleichheit eine natürliche Bedingung oder eine politische Errungenschaft?',
    'Was macht Kunst bedeutsam?',
    'Ist Leiden notwendig für Wachstum?',
    'Was schulden wir zukünftigen Generationen?',
    'Kann es Fortschritt in der Ethik geben?',
    'Was ist die Beziehung zwischen Sprache und Denken?',
    'Gibt es so etwas wie ein Selbst?',
    'Was ist die Natur des Bösen?',
    'Kann die Vernunft allein uns leiten?',
    'Was ist der Zweck des Leidens?',
    'Ist die Demokratie die beste Regierungsform?',
    'Was ist der Unterschied zwischen Wissen und Glauben?',
    'Können wir für das verantwortlich gemacht werden, was wir sind?',
    'Was ist die Beziehung zwischen Körper und Geist?',
    'Gibt es eine objektive Realität?',
    'Was ist Würde?',
    'Was ist die Beziehung zwischen Freiheit und Verantwortung?',
    'Kann Vergeben rational sein?',
    'Was ist Heimat?',
    'Gibt es Bedeutung in der Vergänglichkeit?',
    'Was ist ein guter Tod?',
    'Was schulden wir denen, die vor uns kamen?',
    'Ist Einsamkeit ein philosophisches Problem?',
    'Was ist Stille?',
  ],
};

export const WELCOME_POOL: Record<string, string[]> = {
  English: [
    'A friendly voice in the forest of the mind.',
    'Where the abyss also talks back.',
    'Where does your mind take us today?',
    'Putting the AI back in Aesop.',
    'Can you ask Alexander to get out of our sun?',
    'The first step out of the basement or the first step back into it.',
    'Not all who wander are lost — but it helps to know why you left.',
    'Somewhere between the question and the answer lives the thinking.',
    'The unexamined life is not worth living — so let us examine.',
    'Ideas are the only things worth being afraid of.',
    'Every certainty was once a question.',
    'What you cannot question owns you.',
    'Thinking is the one thing no one can do for you.',
    'The map is not the territory — but it is a good place to start.',
    'You have arrived at the edge of what you already know.',
    'Philosophy begins in wonder. Let us begin.',
    'The question you brought with you is the most important one.',
    'Clarity is hard. Comfort is easy. Let us walk the harder path.',
  ],
  Dutch: [
    'Een vriendelijke stem in het woud van de geest.',
    'Waar de afgrond ook terugpraat.',
    'Waarheen brengen jouw gedachten ons vandaag?',
    'De eerste stap uit de kelder of de eerste stap terug naar binnen.',
    'Denken is het begin van alles.',
    'Waar vragen groter worden dan antwoorden.',
    'Niet alle dwalers zijn verdwaald — maar het helpt te weten waarom je vertrok.',
    'Tussen de vraag en het antwoord leeft het denken.',
    'Een leven zonder zelfonderzoek is het leven niet waard — laten we beginnen.',
    'Wat je niet kunt bevragen, bezit je.',
    'Elke zekerheid was ooit een vraag.',
    'Denken is het enige wat niemand voor je kan doen.',
    'Je bent aangekomen aan de rand van wat je al weet.',
    'Filosofie begint met verwondering. Laten we verwonderd zijn.',
    'Duidelijkheid is moeilijk. Comfort is gemakkelijk. Laten we het moeilijkere pad bewandelen.',
  ],
  French: [
    "Une voix amicale dans la forêt de l'esprit.",
    "Où l'abîme répond aussi.",
    "Où votre esprit nous emmène-t-il aujourd'hui?",
    'Le premier pas hors du sous-sol ou le premier pas pour y retourner.',
    "Penser, c'est le début de tout.",
    'Là où les questions deviennent plus grandes que les réponses.',
    'Tous ceux qui errent ne sont pas perdus — mais il aide de savoir pourquoi on est parti.',
    'Entre la question et la réponse vit la pensée.',
    "La vie non examinée ne vaut pas la peine d'être vécue — examinons.",
    'Ce que vous ne pouvez pas questionner vous possède.',
    'Toute certitude fut jadis une question.',
    'Penser est la seule chose que personne ne peut faire à votre place.',
    'Vous êtes arrivé au bord de ce que vous savez déjà.',
    "La philosophie commence dans l'étonnement. Commençons.",
    'La clarté est difficile. Le confort est facile. Marchons ensemble sur le chemin le plus difficile.',
  ],
  German: [
    'Eine freundliche Stimme im Wald des Geistes.',
    'Wo der Abgrund auch zurückspricht.',
    'Wohin nimmt uns dein Geist heute?',
    'Der erste Schritt aus dem Keller oder der erste Schritt herein.',
    'Denken ist der Anfang von allem.',
    'Wo Fragen größer werden als Antworten.',
    'Nicht alle, die wandern, sind verloren — aber es hilft zu wissen, warum man aufgebrochen ist.',
    'Zwischen der Frage und der Antwort lebt das Denken.',
    'Das ungeprüfte Leben ist nicht lebenswert — also prüfen wir.',
    'Was du nicht hinterfragen kannst, besitzt dich.',
    'Jede Gewissheit war einmal eine Frage.',
    'Denken ist das Einzige, was niemand für dich tun kann.',
    'Du bist am Rand dessen angekommen, was du bereits weißt.',
    'Philosophie beginnt mit Staunen. Lass uns staunen.',
    'Klarheit ist schwer. Komfort ist leicht. Lass uns den schwereren Weg gehen.',
  ],
};