export const FIXED_SUGGESTION: Record<string, string> = {
  English: 'What is wrong with this world?',
  Dutch: 'Wat is er mis met deze wereld?',
  French: "Qu'est-ce qui ne va pas dans ce monde?",
  German: 'Was stimmt nicht mit dieser Welt?',
};

export const SUGGESTION_POOL: Record<string, string[]> = {
  English: [
    'What is time?',
    'What is meaning?',
    'What is value?',
    'Why does something feel right or wrong?',
    'What is justice?',
    'What is the self?',
    'Is free will real?',
    'What is consciousness?',
    'Why do we fear death?',
    'What do we owe each other?',
    'Can we ever truly know anything?',
    'What makes a life well-lived?',
    'Why is there something rather than nothing?',
    'What is beauty?',
    'Is happiness the point of life?',
    'What is truth?',
    'Why do good people do bad things?',
    'What is power?',
    'Can violence ever be justified?',
    'What is love?',
    'Why do humans need meaning?',
    'Is morality invented or discovered?',
  ],
  Dutch: [
    'Wat is tijd?',
    'Wat is betekenis?',
    'Wat is waarde?',
    'Waarom voelt iets goed of fout?',
    'Wat is rechtvaardigheid?',
    'Wat is het zelf?',
    'Is vrije wil echt?',
    'Wat is bewustzijn?',
    'Waarom zijn we bang voor de dood?',
    'Wat zijn we elkaar verschuldigd?',
    'Kunnen we ooit iets echt weten?',
    'Wat maakt een leven de moeite waard?',
    'Waarom bestaat er iets in plaats van niets?',
    'Wat is schoonheid?',
    'Is geluk het doel van het leven?',
    'Wat is waarheid?',
    'Waarom doen goede mensen slechte dingen?',
    'Wat is macht?',
    'Kan geweld ooit gerechtvaardigd zijn?',
    'Wat is liefde?',
    'Waarom hebben mensen betekenis nodig?',
    'Is moraliteit uitgevonden of ontdekt?',
  ],
  French: [
    "Qu'est-ce que le temps?",
    "Qu'est-ce que le sens?",
    "Qu'est-ce que la valeur?",
    'Pourquoi quelque chose semble-t-il juste ou faux?',
    "Qu'est-ce que la justice?",
    "Qu'est-ce que le soi?",
    'Le libre arbitre est-il réel?',
    "Qu'est-ce que la conscience?",
    'Pourquoi craignons-nous la mort?',
    'Que nous devons-nous mutuellement?',
    'Peut-on jamais vraiment savoir quelque chose?',
    "Qu'est-ce qui rend une vie bien vécue?",
    'Pourquoi y a-t-il quelque chose plutôt que rien?',
    "Qu'est-ce que la beauté?",
    'Le bonheur est-il le but de la vie?',
    "Qu'est-ce que la vérité?",
    'Pourquoi les bonnes personnes font-elles de mauvaises choses?',
    "Qu'est-ce que le pouvoir?",
    'La violence peut-elle jamais être justifiée?',
    "Qu'est-ce que l'amour?",
    'Pourquoi les humains ont-ils besoin de sens?',
    'La moralité est-elle inventée ou découverte?',
  ],
  German: [
    'Was ist Zeit?',
    'Was ist Bedeutung?',
    'Was ist Wert?',
    'Warum fühlt sich etwas richtig oder falsch an?',
    'Was ist Gerechtigkeit?',
    'Was ist das Selbst?',
    'Ist freier Wille real?',
    'Was ist Bewusstsein?',
    'Warum fürchten wir den Tod?',
    'Was schulden wir einander?',
    'Können wir jemals wirklich etwas wissen?',
    'Was macht ein Leben lebenswert?',
    'Warum gibt es etwas statt nichts?',
    'Was ist Schönheit?',
    'Ist Glück der Sinn des Lebens?',
    'Was ist Wahrheit?',
    'Warum tun gute Menschen schlechte Dinge?',
    'Was ist Macht?',
    'Kann Gewalt jemals gerechtfertigt sein?',
    'Was ist Liebe?',
    'Warum brauchen Menschen Bedeutung?',
    'Ist Moral erfunden oder entdeckt?',
  ],
};

export const WELCOME_POOL: Record<string, string[]> = {
  English: [
    'A friendly voice in the forest of the mind.',
    'Where the abyss also talks back.',
    'Where does your mind take us today?',
    'Putting the AI back in Aesop.',
    'Can you ask Alexander to get out of our sun?',
    'The first step out of the basement or the first step back into it.',
  ],
  Dutch: [
    'Een vriendelijke stem in het woud van de geest.',
    'Waar de afgrond ook terugpraat.',
    'Waarheen brengen jouw gedachten ons vandaag?',
    'De eerste stap uit de kelder of de eerste stap terug naar binnen.',
    'Denken is het begin van alles.',
    'Waar vragen groter worden dan antwoorden.',
  ],
  French: [
    "Une voix amicale dans la forêt de l'esprit.",
    "Où l'abîme répond aussi.",
    "Où votre esprit nous emmène-t-il aujourd'hui?",
    'Le premier pas hors du sous-sol ou le premier pas pour y retourner.',
    "Penser, c'est le début de tout.",
    'Là où les questions deviennent plus grandes que les réponses.',
  ],
  German: [
    'Eine freundliche Stimme im Wald des Geistes.',
    'Wo der Abgrund auch zurückspricht.',
    'Wohin nimmt uns dein Geist heute?',
    'Der erste Schritt aus dem Keller oder der erste Schritt herein.',
    'Denken ist der Anfang von allem.',
    'Wo Fragen größer werden als Antworten.',
  ],
};
